import = ["~/.config/alacritty/theme/themes/solarized_osaka.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"

decorations = "Buttonless"

opacity = 0.5
blur = true

option_as_alt = "Both"

[font]
normal.family = "MonoLisa Nerd Font"

size = 14
